janis-commerce/mongodb

CHANGELOG.md
README.md
lib/mongodb.js

**CONFIGURACIÓN DE PROTOCOLO**
JCN-108 configuracion de protocolo
[https://fizzmod.atlassian.net/browse/JCN-108](url)
1.1. Se debe poder modificar por configuración si el protocolo al utilizar (definido como MONGODB_URL_PREFIX). Actualmente es siempre es mongodb://, pero Atlas necesita que sea mongodb+srv://1.2. Debe ser configurable por cada dbKey
Se aplicaron los cambios solicitados.

JCN-108-configuracion-de-protocolo

---

CHANGELOG.md
lib/mongodb.js
tests/mongodb-test.js

**JCN-145-ESTANDARIZACION-DE-FECHAS**
JCN-145 MongoDB debe estandarizar fechas
https://fizzmod.atlassian.net/browse/JCN-145
1.1 - Modificar si corresponde  el driver de `MongoDB` para que contenga `dateCreated` para las fechas de creación de un elemento nuevo.
1.2 - Modificar si corresponde  el driver de `MongoDB` para que contenga `dateModified` para las fechas de edición de un elemento existente.
Se cambio el nombre de los cambios de fecha de modificacion, de `lastModified` a `dateModified`

JCN-145-estandarizacion-de-fechas

---

CHANGELOG.md
README.md
lib/mongodb.js
tests/mongodb-test.js

**JCN-140-mongodb-debe-retornar-id-al-insertar**
JCN- 140 mongodb debe retornar id al insertar
https://fizzmod.atlassian.net/browse/JCN-140
1.1 - Se requiere actualizar el paquete de MongoDB
1.2 - Se requiere que al insertar un registro devuelva la ID del mismo en la base de datos.
Se desarrollo el paquete con los requerimientos solicitados. Y además se cambió `save`, el `multiSave` y `multiInsert` los deje como estaban. Se actualizó con el cambio de la estandarización de las fechas.

JCN 140 mongodb debe retornar id al insertar

---

CHANGELOG.md
README.md
lib/index.js
lib/mongodb-filter-wrapper.js
lib/mongodb.js
tests/mongodb-dependencies/filter-wrapper-test.js
tests/mongodb-test.js

Link al ticket
[Escenario #5: Agregar mapeo de filtros para método get](https://fizzmod.atlassian.net/browse/JCN-160)
Descripción del requerimiento
Se agrega el filtro para obtener datos desde Mongo seteando con la misma idea que Query Builder
Descripción de la solución
Se definieron filtros dentro de Filter Wrapper para que reconozca filtros diferentes al 'equal' y se reconocen desde params y los que existen en Model.
Cómo se puede probar?
Probar con los diferentes tipos de filtros para obtener diferentes respuestas.
Screenshots
Necesita deployear queries?
No
Datos extra a tener en cuenta
Si se tiene duda de la estructura verlo en el Readme.md o sino en los tests hay ejemplos.

Jcn 160 filter mapper

---

CHANGELOG.md
README.md
lib/mongodb-filter-wrapper.js
tests/mongodb-dependencies/filter-wrapper-test.js

**JCN-164-NUEVOS-FILTROS**
JCN-164 Nuevos tipos de filtro de texto y búsqueda dentro de un objeto
https://fizzmod.atlassian.net/browse/JCN-164
6.1. Agregar el tipo de filtro de texto, el mismo debe funcionar cómo el search del package Query-Builder (https://github.com/janis-commerce/query-builder/blob/master/docs/Filters.md)
6.2. Agregar la posiblidad de buscar dentro de un object.
6.2.1. Se debe poder enviar el filtro en modo object.
6.2.2. Se deben poder utilizar todos los tipos de filtros conocidos.
6.2.3. Ej. en caso de enviar filters: { foo.bar: 2 } se debería buscar en por los registros que en el dato bar igual a 2 dentro de foo.
6.2.4. Ej. en caso de enviar filters: { dates.created: { type: 'greater', value: '10/10/2019' } } se …

JCN-164-nuevos-filtros

---

lib/mongodb-filter-wrapper.js
tests/mongodb-dependencies/filter-wrapper-test.js

JCN-170 Permitir multiple filtro para el mismo campo de la base
LINK AL TICKET
https://fizzmod.atlassian.net/browse/JCN-170
DESCRIPCIÓN DEL REQUERIMIENTO
7.1. Se requiere dar soporte a multiples filtros aplicados para el mismo campo
7.2. Se deben agrupar los filtros cuando los tipos sean distintos.
7.3. Ej de uso esperado:
En el modelo se encontrarán los fields:
static get fields() {
return {
dateFrom: { field: 'date', type: 'greaterOrEqual' },
dateTo: { field: 'date', type: 'lesserOrEqual' }
};
}
Se podría llamará al filtro con:
const items = await myModel.get({
filters: { dateFrom: '01/10/2019', dateTo: '05/10/2019' }
});
En mongodb deberíamos poder filtrar con:
await db.collection('table').find({
date: { '$gte': '01/10/2019', '$lte': '05/10/2019' }
});
DESCRIPCIÓN DE LA SOLUCIÓN
Se …

Adding filter manipulation if exists another.-

---

lib/mongodb.js

**Link al ticket**
https://fizzmod.atlassian.net/browse/JAN-774
**Descripción del requerimiento**
Se requiere corregir el llamado al metodo `prepareFields` para que se preparen filtros, ya que cuando se envía el filtro id no se están borrando los documentos.
**Descripción de la solución**
Se pasa un `toFilter` en `true` para que cuando se hace el `prepareFields` se preparen filtros y en este caso se agrege lo requerido para que filtre los documentos y los elimine.
**Cómo se puede probar?**
Hacer `multiRemove` pasando como filtro:
- Un id `{ id: .... }`
- Un listado de ids {id: [...]}
- Un status o alguna otra propiedad que no sea en particular un id.
**Screenshots**
No.
**Datos extra a tener en cuenta**
No.
**Changelog**
Fixed: pass to filter flag when prepare fields on multiRemove method

fix the multi remove prepare filters

---

CHANGELOG.md
README.md
lib/helpers/set-on-insert-parser.js
lib/mongodb.js
tests/mongodb.js

https://fizzmod.atlassian.net/browse/JCN-219
​
Se requiere realizar las siguientes modificaciones
- Modificar los métodos `save()` y` multiSave() `para aceptar un parámetro object `setOnInsert`.
- Este objecto opcional debe agregarse en `$setOnInsert`.
- En caso de existir algún campo en la información de cada item, se debe eliminar de` setOnInsert`
​
Se desarrollaron los requerimientos solicitados

JCN 219 agregar set on insert en save multi save

---

CHANGELOG.md
README.md
lib/mongodb.js
tests/mongodb.js

https://fizzmod.atlassian.net/browse/
​
Se requiere devolver los ids de los documentos insertados en mongo cuando se utiliza el método `multiInsert()`
Para hacer esto, se deberá devolver el campo ops que contiene el el array de  items agregándole el `id` y `dateCreated`
Utilizar `ObjectIdHelper.mapIdForClient(`) para devolver los ids correctamente.
​
Se desarrollaron los requerimientos solicitados

JCN 222 MultiInsert devuelve IDs

---

CHANGELOG.md
README.md
lib/mongodb.js
tests/mongodb.js

https://fizzmod.atlassian.net/browse/JCN-321
Se requiere soportar la funcionalidad del **arrayFilters** en el método **update** del package de mongo.
Se debe agregar al método la posibilidad de recibir el parámetro **options** de mongodb para soportar todas las funcionalidades. Ver documentación: https://docs.mongodb.com/v3.6/reference/method/db.collection.updateMany/
- Se modifico el método **update** para soportar el parámetro **options**.
- Se modificaron los test.
- Se modifico el **README** y el **CHANGELOG**.

JCN 322 Soportar el parámetro options en el método update de mongo

---

CHANGELOG.md
README.md
lib/helpers/object-id.js
lib/mongodb-filters.js
lib/mongodb-wrapper.js
tests/mongodb-wrapper.js
tests/mongodb.js

**Links:**
- [Tarea](https://fizzmod.atlassian.net/browse/JCN-355)
- [Subtarea](https://fizzmod.atlassian.net/browse/JCN-356)
**Requerimiento:**
Sumar la validación de una nueva variable de entorno `CLOSE_MONGODB_CONNECTIONS`
Actualmente siempre se cierran las conexiones al escuchar el evento **janiscommerce.ended**
Comportamiento
Tendremos 3 posibilidades para cubrir
Sí `CLOSE_MONGODB_CONNECTIONS` no existe (situación actual y default), se debe cerrar conexiones :white_check_mark: 
Sí `CLOSE_MONGODB_CONNECTIONS` existe con el valor false, no se debe cerrar conexiones :x:
Sí `CLOSE_MONGODB_CONNECTIONS` existe con cualquier otro valor, se debe cerrar conexiones :white_check_mark:   
**Documentación**
Se debe sumar al README.md la variable de entorno y su comportamiento, para que los devs …

Jcn 355 subtarea sumar configuracion para evitar cerrar conexiones mongo

---

CHANGELOG.md
README.md
lib/mongodb.js
tests/mongodb.js

[Subtarea](https://fizzmod.atlassian.net/browse/JCN-367)
El package de [Mongodb](https://github.com/janis-commerce/mongodb) necesita que al actualizar pueda aceptar tanto objectos (el uso actual) como un array de objectos.
Este cambió es importante para poder realizar multiples operaciones sobre los registros.
Ejemplo de Query: [Mongo playground](https://mongoplayground.net/p/R_3UHRYv9r7)
Se desarrollaron los requerimientos solicitados

JCN 367 soportar multiples updates

---

CHANGELOG.md
README.md
lib/helpers/object-id.js
lib/mongodb-error.js
lib/mongodb.js
tests/mongodb.js

https://fizzmod.atlassian.net/browse/JCN-374
Se necesita agregar el soporte para poder usar [Aggregation](https://www.mongodb.com/docs/manual/aggregation/) de Mongodb a través del método [aggregate](https://www.mongodb.com/docs/manual/reference/method/db.collection.aggregate/).
Para esto el método debe cumplir que
Aceptar un array de pipelines con stages para que la base pueda realizar las operaciones.
* por ejemplo para poder usar $match , $group , etc..
* estos stages deben cumplir con poder transformar los id en _id: ObjectId(...) para que la base lo pueda interpretar correctamente
* se debe poder usar $unset como un stage:  
Devolver un array de documentos de los resultados obtenidos.
Se debe documentar esta nueva funcionalidad. …

JCN-374 Agregar soporte aggregates

---

.eslintrc.js
.github/workflows/build-status.yml
.github/workflows/coverage-status.yml
.github/workflows/npm-publish.yml
CHANGELOG.md
lib/mongodb.js
tests/mongodb.js

**Link al ticket:**
[Ticket](https://fizzmod.atlassian.net/browse/JCN-376) || [Subtarea](https://fizzmod.atlassian.net/browse/JCN-377)
**Requerimiento:**
Qué se espera ?
En el package de [mongodb](https://github.com/janis-commerce/mongodb) existe el método save para guardar o actualizar un registro según corresponda. Se espera que este método devuelva el id del registro que creó o actualizó.
Cuál es el problema ?
El problema esta en que cuando crea un registro nuevo no esta devolviendo el id.
Esto sucede porque el package espera sacar esta id del valor value._id, pero esto solo esta sucediendo cuando actualiza un registro y no cuando se crea.
Ejemplo
Asi devuelve el driver al usar save para crear
```
{
lastErrorObject: {
n: 1,
updatedExisting: false,
upserted: new …
```

JCN-377 Corregir en metodo Save la forma de guardar ID de mongo

---

.github/workflows/build-status.yml
.github/workflows/coverage-status.yml
.github/workflows/npm-publish.yml
CHANGELOG.md
lib/helpers/object-id.js
lib/mongodb.js
tests/mongodb.js

https://fizzmod.atlassian.net/browse/
Al utilizar el método update con stages sucede que cuando una de estas stages es $unset.
Lo que sucede es que como aggregation es diferente a no usar stages, se sigue formateando mal y haciendo que las query no funcionen.
> En aggregates este problema no existe
Se desarrollaron los requerimientos solicitados

JCN-381 arreglar unset update

---

CHANGELOG.md
README.md
lib/mongodb.js
tests/mongodb.js

[Historia](https://fizzmod.atlassian.net/browse/JCN-393)
[Subtarea](https://fizzmod.atlassian.net/browse/JCN-394)
Se necesita agregar en el package de :leaves: [GitHub - janis-commerce/mongodb](https://github.com/janis-commerce/mongodb) alguna manera de validar el id necesario para este driver, ya que en este caso es particular, y si se quiere filtrar sin ser del tipo de dato correcto la base va a explotar y no es correcto.
Para esto se necesita crear un nuevo getter llamado idStruct, que retorne una función struct para validar objectId (que es el tipo de id que necesita mongodb).
Este nuevo getter va ser usado tanto por [GitHub - janis-commerce/model](https://github.com/janis-commerce/model) como por [GitHub - janis-commerce/api-get: A package to handle JANIS Views Get …

Jcn 394 add id struct getter

---

README.md
lib/mongodb.js
tests/mongodb.js

Este ajuste es para poder evitar que siempre se sume `dateModified` al update, al mismo tiempo va de la mano con el package de `model` ya que también suma `dateModified`.
Esta el mismo ejemplo explicado en ambos PRs.
El package ya paso por pruebas y fueron correctas comento el escenario que se uso para probar:
En OMS se hizo una lambda que actualiza dos datos puntuales a varios pedidos al mismo tiempo por medio de un filtro, para este ejemplo pongamos tres pedidos.
Sin la flag ósea funcionamiento normal de siempre podemos darle al update 100 veces que siempre va actualizar los tres pedidos, esto pasa porque en todos los casos lo único que se termina actualizando son los campos automáticos.
Con flag y pedidos previamente actualizados, para este caso el resultado es siempre que la cantidad …

Jcn 448 skip automatic date modified

---

README.md
lib/mongodb.js
tests/mongodb.js

https://janiscommerce.atlassian.net/browse/JCN-442
https://janiscommerce.atlassian.net/browse/JCN-445
Se necesita modificar el package de [Mongodb](https://github.com/janis-commerce/mongodb/tree/master) para agregarle al package getTotals que acepte un campo nuevo: filters .
Este nuevo campo va a servir para los casos en los que se quiera obtener los totales de una colección en base a unos filtros, evitando hacer un get con esos filtros antes.
Este campo filters se va a tener que formatear con los helpers del package para que pueda hacer la query correctamente.
En caso que no venga este parametro, debe continuar con el comportamiento habitual
Esto va a servir para que el getTotals sepa calcular los totales segun filtros sin usarse el get con anterioridad
En  /lib/mongodb.js#L433 …

Add filters to getTotal method

---

README.md
lib/mongodb.js
tests/mongodb.js

Link de la tarea
Epica: https://janiscommerce.atlassian.net/browse/JCN-481
Subtarea: https://janiscommerce.atlassian.net/browse/JCN-482
Actualmente nuestros paquetes de Mongo y Model no permiten realizar múltiples operaciones de actualización en una misma query a menos que exista un indice único (`multiSave`)
En este caso, en la tarea https://janiscommerce.atlassian.net/browse/JHUB-38   surge la necesidad de actualizar todos los skus de múltiples productos, lo cual hoy solo es posible de la siguiente manera:
- obteniendo todos los registros
- modificandolos desde codigo
- guardando con un multiSave
Esta misma operación podría hacerse con una sola query que contenga algo similar a esto
```
[{
updateMany: {
filter: { product: '123' },
update: {
$set: {
brand: product1.brand
}
}
}
},
{ …
```

Jcn-482 sumar metodo multiUpdate method

---

lib/mongodb.js
tests/mongodb.js

[historia](https://janiscommerce.atlassian.net/browse/JCN-486)
[subtarea](https://janiscommerce.atlassian.net/browse/JCN-488)
Se requiere modificar el metodo multiUpdate para que acepte pipelines y multiples operadores (hoy automaticamente asigna lo recibido a un $set) dentro de los valores a actualizar en cada operacion.
Dejo pruebas en playground
[Funcionamiento con pipelines](https://www.loom.com/share/66beffbe73e3421d99610422dc9971fa)
[Funcionamiento con updates normales (funcionamiento vigente y que debe continuar)](https://www.loom.com/share/21e83c18531245258145af4059a1f96a)
```
- MultiUpdate method now accepts all available update operators and operations with pipeline aggregations
```

Jcn-488 Adaptar metodo multiUpdate para que acepte multiples operadores y operaciones con pipeline aggregation 
